In [2]:
import numpy as np

### task 1

In [3]:
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7]).reshape((5,2))
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([4.6, 5.8])

### task 2

In [8]:
a_centered = a - mean_a
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])

### task 3

In [16]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp

41.60000000000001

In [19]:
a_centered_sp / (a.shape[0] - 1)

10.400000000000002