#### Задание 1

In [2]:
import numpy as np

In [21]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Задание 2

In [28]:
a_len = len(a)
np_mtrces = []
for x in range(2, 13):
    if len(np_mtrces) == 5:
        break
    if a_len % x == 0:
        np_mtrces.append(a.reshape([x, a_len // x]))
        
for i, x in enumerate(np_mtrces):
    print(i, ':')
    print(x)

0 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
3 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
4 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 3

In [37]:
a_len = len(a)
np_mtrces = []
for x in range(2, 13):
    if len(np_mtrces) == 5:
        break
    if a_len % x == 0:
        if len(np_mtrces) <= 3:
            np_mtrces.append(a.reshape([x, -1]))
        else:
            np_mtrces.append(a.reshape([-1, a_len // x]))
        
for i, x in enumerate(np_mtrces):
    print(i, ':')
    print(x)

0 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
3 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
4 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 4

In [40]:
np.arange(12, 24).reshape([12, 1])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### Назвать можно, но фактически структура данных объекта соответствует двумерному массиву

#### Задание 5