#### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Задание 2

In [3]:
a_len = len(a)
np_mtrces = []
for x in range(2, 13):
    if len(np_mtrces) == 5:
        break
    if a_len % x == 0:
        np_mtrces.append(a.reshape([x, a_len // x]))
        
for i, x in enumerate(np_mtrces):
    print(i, ':')
    print(x)

0 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
3 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
4 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 3

In [4]:
a_len = len(a)
np_mtrces = []
for x in range(2, 13):
    if len(np_mtrces) == 5:
        break
    if a_len % x == 0:
        if len(np_mtrces) <= 3:
            np_mtrces.append(a.reshape([x, -1]))
        else:
            np_mtrces.append(a.reshape([-1, a_len // x]))
        
for i, x in enumerate(np_mtrces):
    print(i, ':')
    print(x)

0 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
3 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
4 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 4

In [5]:
np.arange(12, 24).reshape([12, 1])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### Назвать можно, но фактически структура данных объекта соответствует двумерному массиву

#### Задание 5

In [6]:
a = np.random.normal(loc=0.0, scale=1.0, size=12).reshape([3,4])
print(a.size)
print(a)

12
[[ 1.5009566  -0.99673281  0.84717348  0.34616604]
 [-1.6583599  -0.5551006  -0.33503074  1.06100195]
 [ 0.40820442  2.27264573 -0.67835906 -1.61236473]]


In [7]:
a1 = a.flatten()

In [8]:
print(a1.size)
print(a1)

12
[ 1.5009566  -0.99673281  0.84717348  0.34616604 -1.6583599  -0.5551006
 -0.33503074  1.06100195  0.40820442  2.27264573 -0.67835906 -1.61236473]


#### Задание 6

In [9]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [10]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [11]:
np.array_equal(a, b)

True

##### Разницу не нашел

#### Задание 7 // TODO

In [44]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(c)
print('size:', c.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
size: 10


#### Задание 8

In [13]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
A = np.matrix(a.reshape(4, 3))
A

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [15]:
At = A.T
At

matrix([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [16]:
B = A.dot(At)
B

matrix([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]])

In [17]:
B.shape

(4, 4)

In [18]:
np.linalg.det(B)

0.0

##### Определитель равен 0, так что обратной матрицы не существует

#### Задание 9

In [19]:
np.random.seed(42)

In [20]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [21]:
C = np.matrix(c.reshape(4, 4))
C

matrix([[ 6,  3, 12, 14],
        [10,  7, 12,  4],
        [ 6,  9,  2,  6],
        [10, 10,  7,  4]])

In [22]:
D = C * 10 + B
D

matrix([[ 65,  44, 143, 172],
        [114, 120, 206, 162],
        [ 83, 176, 169, 272],
        [132, 222, 282, 342]])

In [23]:
np.linalg.det(D)

-28511999.999999944

In [24]:
np.linalg.matrix_rank(D)

4

In [25]:
D_inv = np.linalg.inv(D)
D_inv

matrix([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### Задание 10

In [27]:
x, y = D_inv.shape

for i in range(x):
    for j in range(y):
        D_inv[i, j] = 0 if D_inv[i, j] <=0 else 1

E = np.where(D_inv == 1, B, C)
        
print('D_inv:\n', D_inv)
print('B:\n', B)
print('C:\n', C)
print('E:\n', E)

D_inv:
 [[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]
B:
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C:
 [[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
E:
 [[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
