#### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Задание 2

In [3]:
a_len = len(a)
np_mtrces = []
for x in range(2, 13):
    if len(np_mtrces) == 5:
        break
    if a_len % x == 0:
        np_mtrces.append(a.reshape([x, a_len // x]))
        
for i, x in enumerate(np_mtrces):
    print(i, ':')
    print(x)

0 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
3 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
4 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 3

In [4]:
a_len = len(a)
np_mtrces = []
for x in range(2, 13):
    if len(np_mtrces) == 5:
        break
    if a_len % x == 0:
        if len(np_mtrces) <= 3:
            np_mtrces.append(a.reshape([x, -1]))
        else:
            np_mtrces.append(a.reshape([-1, a_len // x]))
        
for i, x in enumerate(np_mtrces):
    print(i, ':')
    print(x)

0 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
3 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
4 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 4

In [5]:
np.arange(12, 24).reshape([12, 1])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### Назвать можно, но фактически структура данных объекта соответствует двумерному массиву

#### Задание 5

In [6]:
a = np.random.normal(loc=0.0, scale=1.0, size=12).reshape([3,4])
print(a.size)
print(a)

12
[[ 3.38405116e-01 -8.54458996e-01 -6.53476116e-01  1.94072489e-01]
 [ 1.52282576e+00  9.50227711e-01  2.41642675e-03  6.37841790e-01]
 [-2.77229124e-01  3.19569644e-01  2.40353208e+00  2.49077246e+00]]


In [7]:
a1 = a.flatten()

In [8]:
print(a1.size)
print(a1)

12
[ 3.38405116e-01 -8.54458996e-01 -6.53476116e-01  1.94072489e-01
  1.52282576e+00  9.50227711e-01  2.41642675e-03  6.37841790e-01
 -2.77229124e-01  3.19569644e-01  2.40353208e+00  2.49077246e+00]


#### Задание 6

In [9]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [10]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [11]:
np.array_equal(a, b)

True

##### Разницу не нашел

#### Задание 7

#### Задание 8

In [14]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
A = np.matrix(a.reshape(4, 3))
A

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [28]:
At = A.T
At

matrix([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [29]:
B = A.dot(At)
B

matrix([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]])

In [30]:
B.shape

(4, 4)

In [31]:
np.linalg.det(B)

0.0

##### Определитель равен 0, так что обратной матрицы не существует